### PR TITLE
Token column added in stat.requests table.

### PR DESCRIPTION
**Pull request by Netmisa**
# Introduction
*Token added in stat.requests table*

## 1. Dependencies
Depends of:
* https://github.com/CanalTP/navitia-proto/pull/33
* https://github.com/CanalTP/navitia/pull/1351
 
## 2. How to run it ?

```
python setup.py build_pbf
python stat_persist.py stat_persistor.json
```

## 3. Migration
*Execute command:*
```
cd migrations && alembic upgrade head
```

### CODE REVIEW

**Comment by lrocheWB** [comment]
Works for me :+1:

**Comment by vincentlepot** [comment]
Hmm.. I'm surprised it works without updating the navitia-proto submodule. Are you REALLY sure?

**Comment by Netmisa** [comment]
@vincentlepot Are you sure you doesn't already update navitia-proto just before ? Because "normaly" you will have an error message [here](https://github.com/CanalTP/navitia-stat-persistor/pull/9/files#diff-2f278657b908609d13e4d37344e76709R132)

Like this :
```
[2016-01-06 09:53:22,118] [ERROR] [ 7271] [stat_persistor] error during transaction
Traceback (most recent call last):
  File "/srv/navitia/navitia-stat-persistor/stat_persistor/saver/statsaver.py", line 115, in __persist
    callback(self.meta, conn, item)
  File "/srv/navitia/navitia-stat-persistor/stat_persistor/saver/stat_request.py", line 57, in persist_stat_request
    request_id = conn.execute(query.values(build_stat_request_dict(stat)))
  File "/srv/navitia/navitia-stat-persistor/stat_persistor/saver/stat_request.py", line 132, in build_stat_request_dict
    'token': stat.token
AttributeError: 'StatRequest' object has no attribute 'token'
[2016-01-06 09:53:22,119] [WARNING] [ 7271] [stat_persistor] error while saving stats: problem the rollback
```

**Comment by Netmisa** [comment]
Thanks @vincentlepot we forget to update submodule of navitia-proto.
PR to fix this : https://github.com/CanalTP/navitia-stat-persistor/pull/11

**Pull request merged**
